language: java

env:
  global:
    - secure: "H1N526kATRcxtJfdxMy_tg"

addons:
  coverity_scan:
    project:
      name: "frc-team-342/frc-team-342-robot-vision"
      version: "0.0.1-SNAPSHOT"
      description: ""

    notification_email: "adam.brightwell@gmail.com"

    build_command: "mvn"

    branch_pattern: "master"
