language: java

env:
  global:
    - secure: "QyF4F2d+XsKE5qJdBY6IMwmFtYHcMK1PNpkEFL14jtqHerxS1hb+sTnLvbHT6BsKh7UsTThkMB80jDB26GkHLcgrfAgDlx7VUWeQ9ZDcYO1Svlv89dXQvOEFnQy2UTw+c6Eea1MUW3fI2L/KZ0A3oJBgN+rfJwKG5r1sGZcID4w="

addons:
  coverity_scan:
    project:
      name: "frc-team342-robot-vision"
      version: "0.0.1-SNAPSHOT"
      description: ""

    notification_email: "adam.brightwell@gmail.com"

    build_command: "mvn"

    branch_pattern: "master"
